class Solution {
public:
        string intToRoman(int n) {
string s="";
       while(n>=1000){
          s=s+'M';
          n=n-1000;
       }
       if(n>=900){
          s=s+"CM";
          n=n-900;
       }
       if(n>=500){
          s=s+'D';
          n=n-500;
       }
       if(n>=400){
          s=s+"CD";
          n=n-400;
       }
       while(n>=100){
          s=s+'C';
          n=n-100;
       }
       if(n>=90){
          s=s+"XC";
          n=n-90;
       }
       if(n>=50){
          s=s+'L';
          n=n-50;
       }
       if(n>=40){
          s=s+"XL";
          n=n-40;
       }
      while(n>=10){
          s=s+'X';
          n=n-10;
       }
       if(n>=9){
          s=s+"IX";
          n=n-9;
       }
       if(n>=5){
          s=s+'V';
          n=n-5;
       }
       if(n>=4){
          s=s+"IV";
          n=n-4;
       }
       while(n--){
          s=s+"I";
       }
    return s;
}
};
